added destructors
NOAA-FIMS/FIMS pull request #231
Opened 2022-09-08 18:46 UTC by msupernaw

Thanks for opening a pull request (PR) to FIMS! Please describe the changes under the headings below. Please also go through the checklist below to ensure the appropriate steps have been taken during development. For smaller changes, feel free to skip steps that aren't relevant, but at least describe the feature under the "what is the feature".

# What is the feature?
A brief title of this change.

# How have you implemented the solution?
Describe the changes.

# Does it impact any other area of the project?
Please describe which features are impacted by this change.

# Does this change impact the model input or output?*
Please describe any way this change impacts the model input or output.

# How to test this change
Please include a test file and/or Github workflow.

# Developer pre-PR Checklist

Please do these steps locally for big changes. Note GitHub Actions does all of these checks automatically when pushing to the repository. Please see [code development section in the contributor guide](https://noaa-fims.github.io/collaborative_workflow/contributor-guidelines.html#code-development) for details.

- [ ] Run [cmake build and ctest locally](https://noaa-fims.github.io/collaborative_workflow/testing.html#c-unit-testing-and-benchmarking) and make sure the C++ tests pass
- [ ] Run `devtools::document()` locally and push changes to the remote feature branch
- [ ] Run `styler::style_pkg()` locally and push changes to remote feature branch. If there are many changes, please do this in a separate commit.
- [ ] Run `devtools::check()` locally and make sure the package can be compiled and R tests pass. If there are failing tests, run `devtools::test(filter = "file_name")` (where "test-file_name.R" is the testthat file containing failing tests) and edit code/tests to troubleshoot tests.
- [ ] Before opening the PR, make sure all the github actions are passing on the remote feature branch.
- [ ] Make sure this PR has an informative title.

2022-09-08 20:57 UTC, k-doering-NOAA commented
Thanks @msupernaw ! Sorry I didn't clearly communicate that this could be checked on later, but it would be great to add these into the code. Thanks for working on this so quickly! 

I think some accidental .DS_store files crept into this request?  I can force push a new commit to get rid of them from the git history completely and maybe add them to .gitignore so it doesn't happen again. Let me know if you would like me to do this.

@Bai-Li-NOAA , I think you brought up the destructors - does this PR look good to you? I think it does to me, but I don't really understand destructors :)

2022-09-09 13:15 UTC, Bai-Li-NOAA commented on inst/include/common/model.hpp
> +
Do we need a constructor above the destructor? For example, `model(){}`

2022-09-09 13:30 UTC, Bai-Li-NOAA commented on inst/include/common/model_object.hpp
> +    virtual ~FIMSObject(){
Do we need a destructor if we are not allocating any memory here?

2022-09-09 13:37 UTC, Bai-Li-NOAA requested changes
Thanks @msupernaw. The changes look good to me. I do have a question about the destructor. Do we need a destructor if we are not allocating any memory in the model class and the FIMSObject struct? Or do we need to add a matching constructor for the model class and the FIMSObject struct?

@k-doering-NOAA, I agree. Getting rid of the .DS_store files and adding them to .gitignore before merging is a great idea.

2022-09-09 17:33 UTC, k-doering-NOAA commented
I squashed and force pushed to rm the .DS_Store files entirely from the git history, and added .DS_Store to the gitignore. Matthew, note this will make your local out of sync with the remote, so you may need to [reset it](https://stackoverflow.com/questions/1628088/reset-local-repository-branch-to-be-just-like-remote-repository-head)

2022-09-12 19:05 UTC, Bai-Li-NOAA approved these changes

2022-09-12 19:06 UTC, merged

2022-09-12 19:07 UTC, Bai-Li-NOAA reviewed
The changes look good!