Feat issue 17 logistic selectivity module
NOAA-FIMS/FIMS pull request #31
Opened 2022-03-21 15:08 UTC by Andrea-Havron-NOAA

**What is the feature?** 
The logistic selectivity module

**How have you implemented the solution?** 
- new [fims_math.hpp](https://github.com/NOAA-FIMS/FIMS/blob/feat-issue-17-logistic-selectivity-module/inst/include/fims_math.hpp) file under [inst/include](https://github.com/NOAA-FIMS/FIMS/tree/feat-issue-17-logistic-selectivity-module/inst/include)
  - logistic() function added as an inline const T
- new [functors](https://github.com/NOAA-FIMS/FIMS/tree/feat-issue-17-logistic-selectivity-module/inst/include/population_dynamics/selectivity/functors) folder under [inst/include/population_dynamics/selectivity](https://github.com/NOAA-FIMS/FIMS/tree/feat-issue-17-logistic-selectivity-module/inst/include/population_dynamics/selectivity)
  - [selectivity_base.hpp](https://github.com/NOAA-FIMS/FIMS/blob/feat-issue-17-logistic-selectivity-module/inst/include/population_dynamics/selectivity/functors/selectivity_base.hpp): develop initial selectivity base struct with evaluate function
  - [logistic.hpp](https://github.com/NOAA-FIMS/FIMS/blob/feat-issue-17-logistic-selectivity-module/inst/include/population_dynamics/selectivity/functors/logistic.hpp): develop logistic selectivity struct that assigns the logistic function from fims_math to the evaluate function call
- edited [inst/include/population_dynamics/selectivity.hpp](https://github.com/NOAA-FIMS/FIMS/blob/feat-issue-17-logistic-selectivity-module/inst/include/population_dynamics/selectivity/selectivity.hpp): added `#include "functors/selectivity_base.hpp"` to link changes

**Does it impact any other area of the project? Please describe which features are impacted by this change.**
This change does not impact any other area of the project.

**Does this change impact the model input or output? Please describe any way this change impacts the model input or output.**
This change does not impact the model input or output as the selectivity module is not yet linked up to the objective function, [src/FIMS.cpp](https://github.com/NOAA-FIMS/FIMS/blob/feat-issue-17-logistic-selectivity-module/src/FIMS.cpp)

**How to test this change Please include a test file and/or Github workflow.**
- [tests/gtest/test/test_fims_math.cpp](https://github.com/NOAA-FIMS/FIMS/blob/feat-issue-17-logistic-selectivity-module/tests/gtest/test_fims_math.cpp): tests added to test the logistic function in fims_math.hpp

2022-03-21 19:24 UTC, ChristineStawitz-NOAA requested changes
test

2022-03-21 19:32 UTC, JaneSullivan-NOAA commented on inst/include/fims_math.hpp
> +
minimize use of whitespace https://google.github.io/styleguide/cppguide.html#Vertical_Whitespace

2022-03-21 19:39 UTC, JaneSullivan-NOAA commented on inst/include/population_dynamics/selectivity/functors/logistic.hpp
> +    T a50;
Has the group decided on 'T' vs 'Type'?

2022-03-21 19:41 UTC, JaneSullivan-NOAA commented on inst/include/population_dynamics/selectivity/functors/logistic.hpp
> +};
is this semicolon needed?

2022-03-21 19:42 UTC, EJDick-NOAA commented on inst/include/fims_math.hpp
> +
Needs documentation

2022-03-21 19:48 UTC, Bai-Li-NOAA commented on inst/include/fims_math.hpp
> +inline const T logistic(const T& mean, const T& slope, const T& x) {
Define terms used in code line 58. In particular, mean and slope. “Mean” is an index of 50% of function output, probably better termed median. “Slope” is typically a multiplicative scalar and not an inverse multiplier, probably better termed “inverse slope”

2022-03-21 19:50 UTC, Bai-Li-NOAA commented on inst/include/fims_math.hpp
> +    return (1.0) / (1.0 + exp(-1.0 * (x - mean) / slope));
The logistic equation does not match the FIMS design specification document (https://noaa-fims.github.io/collaborative_workflow/m1-model-specification.html#logistic-function-with-extensions); need to use difference in the index at 50% and the index at 95% for the parameterization as in the workflow specs

2022-03-21 19:52 UTC, EJDick-NOAA commented on inst/include/population_dynamics/selectivity/functors/logistic.hpp
> +        return fims::logistic<T>(a50, slope, age);
Consider having users input a50 & a95, with estimation using slope parameterization

2022-03-21 19:56 UTC, EJDick-NOAA requested changes
1. Fix issue with the build; test case number 2 exp.use_integer_inputs failed

- [ ] The code is well-designed.
- [ ] The functionality is good for the users of the code.
- [ ] Any User Interface changes are sensible and look good.
- [ ] Any parallel programming is done safely.
- [ ] The code isn’t more complex than it needs to be.
- [ ] The developer isn’t implementing things they might need in the future but don’t know they need now.
- [ ] Code has appropriate unit tests.
- [ ] Tests are well-designed.
- [ ] The developer used clear names for everything.
- [ ] Comments are clear and useful, and mostly explain why instead of what.
- [ ] Code is appropriately documented (doxygen and roxygen).
- [ ] The code conforms to our style guides.

2022-03-21 19:57 UTC, Bai-Li-NOAA commented on tests/gtest/test_fims_math.cpp
> +    double mean = 3.0;
Expand the test suite and try different input values.

2022-03-22 22:14 UTC, Bai-Li-NOAA commented
> Test number 2 is failing in build workflow

I updated the test and created an issue #41 for resolving the failed test.

2022-03-26 17:45 UTC, ChristineStawitz-NOAA approved these changes
approving Bai's testing changes!

2022-03-29 20:56 UTC, iantaylor-NOAA reviewed
Matching the parameterization used in the model comparison project seems reasonable but differs from our model specification document: https://noaa-fims.github.io/collaborative_workflow/m1-model-specification.html#logistic-function-with-extensions. 

I'm a fan of the parameterization in the collaborative workflow doc, and I think that either one  will work fine for replicating the model comparison project results, but I also see the simplicity of comparing parameters within the same parameterization which this commit enables.

[edit: to clarify, it's recent commit 7ce1694c00056713791a1ee2d6d9b62c104652d0 that I'm referring to--probably should have commented on the individual lines instead of as a code review comment]

2022-05-03 16:33 UTC, closed without merging