doc: error and progress logging for information.hpp
NOAA-FIMS/FIMS pull request #424
Opened 2023-07-20 20:23 UTC by nathanvaughan-NOAA

Added progress and error logging to information.hpp

# What is the feature?

* 

# How have you implemented the solution?

# Does the PR impact any other area of the project?

# How to test this change

# Developer pre-PR checklist

- [x] I relied on GitHub actions to :test_tube: things for me while I sat on the :couch_and_lamp:.

2023-08-08 23:06 UTC, Cole-Monnahan-NOAA requested changes
I was able to successfully build and test this PR locally. It outputs to fims.log in the root directory, but because output is appended it is difficult to parse and check functionality b/c its unclear if errors are expected or not. The only mandatory changes I suggest are to fix address location printing. A few suggestions for discussion/consideration:

1. File should not append from previous runs. How will this work when we run multiple FIMS models in parallel?
2. The file is very hard to read. I suggest more white space to indent like regions (e.g., all likelihood checks for a given fleet), and breaks between major sections (e.g., selex and growth). 
3. I mentioned it below but I don't think printing the whole data set to the log is necessarily a good idea. I suggest we consider just printing the first and last 3 observations. It's possible something can go wrong in other years, but the user won't detect that from this file. Instead, I think that FIMS should check for invalid individual likelihood components as it calculates them and be able to error and with informative messages like "nll for age comps for fleet 1 year 35 is invalid" then print the observed and expected before exiting.

2023-08-18 21:31 UTC, nathanvaughan-NOAA commented on inst/include/common/information.hpp
> +          FIMS_LOG << "Observed input index: \n " << f->observed_index_data
Fixed this it now just prints the first value. We would need extra code in the future to loop and print more/all of the data.

2023-08-18 21:32 UTC, nathanvaughan-NOAA commented on inst/include/common/information.hpp
> +          FIMS_LOG << "Error: Expected data observations not defined for fleet"
Good point I agree. I didn't catch that. I have added exit calls in all failure cases.

2023-08-18 21:34 UTC, nathanvaughan-NOAA commented on inst/include/common/information.hpp
> +          FIMS_LOG << "Age comp data successfully set." << std::endl;
At the moment I've fallen back to just printing the first value. We will need looping code to print out more and I agree it's questionable what we even want to print. Personally, I only use the SS data logs to see when the model has read something different than what I expected to identify a missing conditional input or similar issue. Given the way FIMS is setup I don't think this should ever be a problem so it's unlikely this is needed. We can discuss options at the meeting next week though.

2023-08-18 21:37 UTC, nathanvaughan-NOAA commented on inst/include/common/information.hpp
> +          FIMS_LOG << "Age comp data successfully set." << std::endl;
I have also set up the logging to send logs to their own folder/subfolders. An interesting benefit I found was that if the folder doesn't exist then the log files are not created. We need to do some timed tests to see the impact on runtime but hopefully this is a simple way for the user to determine which if any log files to create we could also add flags to the input code but that will take more code/effort.

2023-08-29 23:37 UTC, ChristineStawitz-NOAA approved these changes

2023-08-30 13:48 UTC, kellijohnson-NOAA commented
Given that this is just a branch and not the main trunk, I would suggest that the commit history be fixed to just wipe out the last four commits and roll it back to [34617f5](https://github.com/NOAA-FIMS/FIMS/pull/424/commits/34617f5d3a53f4219079d4ddb334420ef00e6c2e). This can easily be done with 
```
git reset --h 34617f5
git push -f origin 407-information-logs
```
or through an interactive rebase which is easier with git lens where you can just choose to drop the last four commits. I am happy to do either option or walk someone through the steps so that others can learn. But in my opinion there is no reason to push four commits that we essentially do not want into main.

2023-08-31 17:40 UTC, nathanvaughan-NOAA commented
Thanks Cole, in response to comments:
1) File should not append from previous runs. How will this work when we run multiple FIMS models in parallel?
a) The file is no longer appending it is just running 4 iterations of create_model() one for each AD level.

2) The file is very hard to read. I suggest more white space to indent like regions (e.g., all likelihood checks for a given fleet), and breaks between major sections (e.g., selex and growth).
a) Agree with this, I have pulled most of the other things out of the file but still need to figure out how to do useful indenting when each line of the file is written independently?

3) I mentioned it below but I don't think printing the whole data set to the log is necessarily a good idea. I suggest we consider just printing the first and last 3 observations. It's possible something can go wrong in other years, but the user won't detect that from this file. Instead, I think that FIMS should check for invalid individual likelihood components as it calculates them and be able to error and with informative messages like "nll for age comps for fleet 1 year 35 is invalid" then print the observed and expected before exiting.
a) For now I have modified this to just print the first value of the data file. We will need to create loops to print multiple values or nans but I agree that that is probably unneeded overhead at the moment.

2023-08-31 19:48 UTC, ChristineStawitz-NOAA commented
@Cole-Monnahan-NOAA see Nathan's response - I think you need to approve that he has addressed your comments before we can merge this in. 

We are planning to fix the issue of four runs being printed after we merge in pull request #453 since the Rcpp refactor will change where it needs to be written to the log.

and thanks @kellijohnson-NOAA for giving me the emotional support and git syntax I needed to do a hard reset.

2023-09-07 03:23 UTC, Cole-Monnahan-NOAA approved these changes

2023-09-07 17:51 UTC, merged