Rename testthat files
NOAA-FIMS/FIMS pull request #571
Opened 2024-05-02 17:36 UTC by k-doering-NOAA

# What is the feature?

* Rename the testthat files as proposed in https://github.com/NOAA-FIMS/collaborative_workflow/issues/63.

# How have you implemented the solution?

This includes: 
1) renaming/combining testthat files that correspond with testing R files match the convention `test-name_of_r_file.R` 
2) renaming test of rcpp interface to the convention `test-rcpp-description.R` (where `description` describes the interface being tested.
3) renaming integration tests (currently 1 file) to `test-integration-description.R` (where `description` describes the integration test).

# Does the PR impact any other area of the project?

# How to test this change

Make sure GitHub actions are passing and that filenames are as described

# Developer pre-PR checklist

- [x] I relied on GitHub actions to :test_tube: things for me while I sat on the :couch_and_lamp:.

2024-05-07 15:20 UTC, kellijohnson-NOAA commented on tests/testthat/test-rcpp-get-parameter-vector.R
Should this one be renamed to test-rcpp-get_fixed.R?

2024-05-07 15:24 UTC, kellijohnson-NOAA commented on tests/testthat/test-fimsframe.R
Should the file name be in the same case as the function name, i.e., test-FIMSFrame?

2024-05-07 15:26 UTC, kellijohnson-NOAA requested changes
I made two comments about the file names but other than that everything looks good to merge this into main tomorrow.

2024-05-08 17:29 UTC, kellijohnson-NOAA commented
@k-doering-NOAA I made two comments on this PR that I am not entirely sure if they are valid or not. Once those are addressed we can merge it in.

2024-05-08 23:21 UTC, k-doering-NOAA commented on tests/testthat/test-fimsframe.R
I think it should be the same as the filename that the function FIMSFrame is in, which is `fimsframe.R`. However, do you think we should modify the file names to be more consistent with the function name?

2024-05-08 23:23 UTC, k-doering-NOAA commented on tests/testthat/test-rcpp-get-parameter-vector.R
Sorry, I can't follow why - but if that name feels more appropriate to what the test does, I think it can be renamed!

2024-05-08 23:24 UTC, k-doering-NOAA commented
@kellijohnson-NOAA sorry this took so long - I just replied to your comments. Feel free to decide based on my comments if the changes should be made and merge it in when ready (Or, I'm happy to make the changes if you prefer, just let me know what you think makes sense)!

2024-05-09 13:49 UTC, kellijohnson-NOAA commented on tests/testthat/test-rcpp-get-parameter-vector.R
I just made the suggestion because it seems like we are testing a specific Rcpp function called get_fixed.

Somewhere in the FIMS code it says the following
```
get_fixed function is an Rcpp function that loops over all Rcpp
modules and returned a vector of parameters being estimated
```

2024-05-09 15:29 UTC, k-doering-NOAA commented on tests/testthat/test-rcpp-get-parameter-vector.R
Good catch! I just changed the name to test-rcpp-get_fixed.R.

2024-05-09 15:45 UTC, kellijohnson-NOAA approved these changes

2024-05-09 15:47 UTC, merged