Refactor distribution names
NOAA-FIMS/FIMS pull request #685
Opened 2024-11-18 20:37 UTC by msupernaw

# What is the feature?
* 

# How have you implemented the solution?
* 

# Does the PR impact any other area of the project, maybe another repo?
*

2024-11-22 17:02 UTC, kellijohnson-NOAA requested changes
- [ ] `devtools::document()` needs to be ran
- [ ] we follow a no-merge policy, this is not a big deal here because the commits will be squashed anyway ... but in the future please use `git fetch -a` `git rebase --autostash origin/<branch name>`

@msupernaw I know that you are off today so I might take a stab at some of these things.
@Bai-Li-NOAA this PR is to your dev branch because the changes impact the R interface, do you mind if after the changes are made to the PR that it be brought into your branch?

2024-11-22 17:29 UTC, Bai-Li-NOAA commented
@kellijohnson-NOAA, works for me! Thanks @msupernaw for the refactoring work!

2024-11-25 16:04 UTC, kellijohnson-NOAA commented on inst/include/interface/rcpp/rcpp_objects/rcpp_distributions.hpp
@msupernaw can you confirm that this change is correct?

2024-11-25 18:44 UTC, kellijohnson-NOAA commented on vignettes/fims-demo_files/figure-gfm/plots-2.png
This figure should not have been committed I do not think.

2024-11-25 18:45 UTC, kellijohnson-NOAA commented on inst/include/interface/rcpp/rcpp_objects/rcpp_interface_base.hpp
> +        if (static_cast<size_t>(pos) == 0 || static_cast<size_t>(pos) > this->storage_m->size()) {
This change should be in #662 not here because it doesn't have anything to do with renaming. I am making a note in the issue now.

2024-11-25 19:56 UTC, merged